# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:38
from __future__ import unicode_literals

import advertising.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdAlign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('align', models.CharField(max_length=255, verbose_name='Align')),
            ],
            options={
                'verbose_name_plural': 'Ads align',
                'verbose_name': 'Ads align',
            },
        ),
        migrations.CreateModel(
            name='AdPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('additional', models.CharField(blank=True, max_length=255, verbose_name='Additional info')),
            ],
            options={
                'verbose_name_plural': 'Ads pages',
                'verbose_name': 'Ads page',
            },
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='ID')),
                ('template', models.CharField(help_text='Path to template', max_length=255, verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Ads types',
                'verbose_name': 'Ads type',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(default=datetime.datetime.today, verbose_name='Start date')),
                ('end_date', models.DateField(default=advertising.models.week_delta, verbose_name='End date')),
                ('align', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.AdAlign', verbose_name='Ads align')),
                ('pages', models.ManyToManyField(to='advertising.AdPage', verbose_name='Ads pages')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.AdType', verbose_name='Ads type')),
            ],
            options={
                'verbose_name_plural': 'Реклама',
                'verbose_name': 'Реклама',
            },
        ),
        migrations.AlterUniqueTogether(
            name='adtype',
            unique_together=set([('name',)]),
        ),
    ]
