version: '3'

services:
  django:
    image: pythondigest/pythondigest:${COMMIT_TAG}
    container_name: pydigest_django
    volumes:
      - ${PWD}/static:/app/static/
      - ${PWD}/media:/app/media/
      - ${PWD}/dataset:/app/dataset/
      - ${PWD}/pages:/app/pages/
      - ${PWD}/report:/app/report/
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "
      echo 'Prepare and run'
      && echo 'Migrate migrations'
      && python manage.py migrate --no-input
      && python manage.py collectstatic --no-input
      && cp /app/humans.txt /app/static/
      && cp /app/robots.txt /app/static/
      && uwsgi --ini deploy/uwsgi.ini"
    networks:
      - py_digest
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/ping')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

networks:
  py_digest:
    external: true
