ARG PYTHON_VERSION=3.4.10-slim-jessie

# define an alias for the specfic python version used in this file.
FROM python:${PYTHON_VERSION}

# Install apt packages
RUN apt-get update && apt-get install --no-install-recommends -y --force-yes build-essential libpq-dev \
  python3-all-dev \
  libffi-dev \
  git && python -m pip install -U pip poetry

# Requirements are installed here to ensure they will be cached.
COPY pyproject.toml poetry.lock ./
RUN poetry export -f requirements.txt -o requirements.txt

# Create Python Dependency and Sub-Dependency Wheels.
RUN pip wheel --wheel-dir /usr/src/app/wheels -r requirements.txt
