ARG PYTHON_VERSION=3.4.10-slim-jessie

# define an alias for the specfic python version used in this file.
FROM python:${PYTHON_VERSION}

# Install apt packages
RUN apt-get update && apt-get install --no-install-recommends -y --force-yes build-essential libpq-dev \
  python3-all-dev \
  libffi-dev \
  git && python -m pip install -U pip poetry

ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR ${APP_HOME}

# copy application code to WORKDIR
COPY . ${APP_HOME}

# RUN pip install "pytest-runner==5.2" "django-concurrency==1.3.1" "pynacl==1.4.0" && poetry install

# RUN poetry update
