# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:48
from __future__ import unicode_literals

import django.db.models.manager
import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('digest', '0036_auto_20160322_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCls',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Новости (классификатор)',
                'proxy': True,
            },
            bases=('digest.item',),

        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem', to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
