# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:55
from __future__ import unicode_literals

import taggit_autosuggest.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('digest', '0037_auto_20160330_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem', to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
