# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:03
from __future__ import unicode_literals

import taggit_autosuggest.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('digest', '0040_auto_20160330_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True,
                                                              help_text='A comma-separated list of tags.',
                                                              through='digest.KeywordGFK',
                                                              to='digest.Keyword',
                                                              verbose_name='Keywords'),
        ),
    ]
