# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0041_auto_20160401_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimportresource',
            name='link',
            field=models.URLField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='autoimportresource',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название источника'),
        ),
    ]
