# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0044_auto_20160503_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimportresource',
            name='excl',
            field=models.TextField(blank=True, default='', help_text='List of exceptions, indicate by ", "', verbose_name='Exceptions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoimportresource',
            name='incl',
            field=models.CharField(blank=True, default='', help_text='Условие отбора новостей <br />                    Включение вида [text] <br />                    Включение при выводе будет удалено', max_length=255, verbose_name='Required content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='issues', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='trend',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Trend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='additionally',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Additional info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
