# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('digest', '0045_auto_20160503_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_path',
            field=models.FilePathField(blank=True, default='',
                                       verbose_name='Article path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='additionally',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Additional info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='',
                                   verbose_name='Description'),
            preserve_default=False,
        ),
    ]
