# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0045_auto_20160503_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_path',
            field=models.FilePathField(blank=True, default='', verbose_name='Article path'),
            preserve_default=False,
        ),
    ]
