# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('digest', '0046_auto_20160503_2157'),
    ]

    operations = [

        migrations.AlterField(
            model_name='item',
            name='additionally',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Additional info'),
            preserve_default=False,
        ),

    ]
