# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('digest', '0047_auto_20160509_1114'),
    ]

    operations = [

        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='',
                                   verbose_name='Description'),
            preserve_default=False,
        ),

    ]
