# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0050_auto_20160509_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_editors_choice',
            field=models.BooleanField(default=True, verbose_name='Is editors choice'),
        ),
    ]
