# Generated by Django 4.1.3 on 2022-12-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("digest", "0051_auto_20170220_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="article_path",
            field=models.FilePathField(
                blank=True,
                path="/home/axsapronov/Develop/Groups/PythonDigest/pythondigest/dataset",
                verbose_name="Article path",
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="keywordgfk",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_tagged_items",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="keywordgfk",
            name="object_id",
            field=models.IntegerField(db_index=True, verbose_name="object ID"),
        ),
        migrations.AlterField(
            model_name="keywordgfk",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="digest.keyword",
            ),
        ),
    ]
