# Generated by Django 4.1.3 on 2022-12-05 17:38

from django.db import migrations, models

def migrate_autoimportresource_is_active(apps, schema_editor):
    AutoImportResource = apps.get_model('digest', 'AutoImportResource')

    for x in AutoImportResource.objects.all():
        x.is_active = not x.in_edit
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0053_alter_autoimportresource_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoimportresource",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.RunPython(migrate_autoimportresource_is_active, migrations.RunPython.noop)
    ]
