name: backup

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  backup_database:
    name: Backup PostgreSQL Database
    runs-on: ubuntu-22.04
    environment: production
    steps:
      #----------------------------------------------
      # Copy backup script to server. Load repo
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      #----------------------------------------------
      # Copy backup script
      #----------------------------------------------
      - name: copy backup scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy/postgres/maintenance/backup_on_server.bash,deploy/postgres/maintenance/copy_backup_on_server.bash"
          target: "pythondigest/"

      #----------------------------------------------
      # Make backup
      #----------------------------------------------
      - name: make backup
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            export POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}"
            export POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"

            # change folder
            cd ~/pythondigest/deploy/postgres/maintenance/

            # make backup
            bash backup_on_server.bash

      #----------------------------------------------
      # Upload backup to drive
      #----------------------------------------------
      - name: upload backup to drive
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # change folder
            cd ~/pythondigest/deploy/postgres/maintenance/

            # upload backups to drive
            screen -dmS backup-postgresql-rsync bash copy_backup_on_server.bash

  backup_media:
    name: Backup media
    runs-on: ubuntu-22.04
    environment: production
    steps:
      #----------------------------------------------
      # Copy backup script to server. Load repo
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      #----------------------------------------------
      # Copy backup script
      #----------------------------------------------
      - name: copy backup scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy/postgres/maintenance/copy_media_on_server.bash"
          target: "pythondigest/"

      #----------------------------------------------
      # Upload media to drive
      #----------------------------------------------
      - name: upload media files to drive
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # change folder
            cd ~/pythondigest/deploy/postgres/maintenance/

            # upload media files to drive
            screen -dmS backup-media-rsync bash copy_media_on_server.bash

  backup_zips:
    name: Backup dataset/pages
    runs-on: ubuntu-22.04
    environment: production
    steps:
      #----------------------------------------------
      # Copy backup script to server. Load repo
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      #----------------------------------------------
      # Copy backup script
      #----------------------------------------------
      - name: copy backup scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy/postgres/maintenance/copy_zips_on_server.bash"
          target: "pythondigest/"

      #----------------------------------------------
      # Upload zips to drive
      #----------------------------------------------
      - name: upload zip files to drive
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # change folder
            cd ~/pythondigest/deploy/postgres/maintenance/

            # upload zip files to drive
            screen -dmS backup--zips-rsync bash copy_zips_on_server.bash
